### ISSUE TITLE
StatGit generated pages are loading as blanks

### ISSUE THREAD

**Issue by waldo795** [soundasleep/statgit#1]
I've installed Cloc, cloned stat git and pointed statgit to a working repo as per instructions.

Once I run statgit for the first time I get an undefined index for various pages and the reports are generated with no information.

If there's any log files I can provide to help let me know.

**Comment by waldo795** [comment]
After digging around in the code it appears to be an issue with either the Database.json and the way it's saved or the access of the data i.e. (SummaryStats.php > getTotalLoc() )

```
foreach ($stats as $language) {
 $total += $language["code"];
}
```

For some reason code is never set. There are other instances of this.

**Comment by soundasleep** [comment]
It sounds like it's not able to load the Cloc statistics properly. What version of Cloc are you running? Can you paste in a log of the output?

**Comment by soundasleep** [comment]
And maybe post a copy of your database.json somewhere?
